#!/bin/bash
set -e -x

###
# Making sure curl is installed
###
apt-get update
apt-get install -y curl
###
# Installing Docker
###
apt-get purge "lxc-docker*" || true
apt-get purge "docker.io*" || true
apt-get install -y \
  apt-transport-https \
  ca-certificates \
  gnupg2
apt-key adv \
  --keyserver hkp://ha.pool.sks-keyservers.net:80 \
  --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo debian-jessie main" > /etc/apt/sources.list.d/docker.list
apt-get update
apt-get install -y \
  docker-engine=1.11.2-0~jessie
###
# Cleaning Image
###
apt-get clean
