#!/bin/sh
set -e -x
###
# Adding new entrypoint
###
mv /resources/dockerd-entrypoint /usr/local/bin
mv /resources/jenkins-slave /usr/local/bin
###
# Installing needed Packages
###
apk add --update --no-cache \
  python2=$PYTHON2_VERSION \
  openjdk8=$JAVA_VERSION \
  bzr=$BZR_VERSION \
  git=$GIT_VERSION \
  mercurial=$MERCURIAL_VERSION \
  openssh-client=$OPENSSH_VERSION \
  subversion=$SUBVERSION_VERSION \
  procps=$PROCPS_VERSION \
  bzip2=$BZIP2_VERSION \
  unzip=$UNZIP_VERSION \
  xz=$XZ_VERSION \
  jq=$JQ_VERSION \
  iptables=$IPTABLES_VERSION \
  e2fsprogs=$E2FSPROGS_VERSION \
  wget=$WGET_VERSION \
  bash=$BASH_VERSION
###
# Installing jnlp
###
curl --create-dirs \
     -sSLo /usr/share/jenkins/slave.jar \
     https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar
chmod 755 /usr/share/jenkins
chmod 644 /usr/share/jenkins/slave.jar
###
# Installing Google Cloud SDK
###
cd /resources
wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GCLOUDSDK_VERSION}-linux-x86_64.tar.gz
tar -xzf /resources/google-cloud-sdk-${GCLOUDSDK_VERSION}-linux-x86_64.tar.gz
mv google-cloud-sdk /opt
###
# Installing kubectl
###
curl -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
chmod +x ./kubectl
mv ./kubectl /usr/local/bin/kubectl
