#!/bin/sh

set -e

# Launching Docker in background
dockerd \
  --host=unix:///var/run/docker.sock \
  --host=tcp://0.0.0.0:2375 \
  --mtu 1400 \
  --storage-driver=vfs &

# Launching jnlp slave
exec jenkins-slave "$@"
